c
c Copyright (c) 1996-2004 by Gennady Serdyuk.  All rights reserved.
c gserdyuk@mail.ru
c
c Released under GPL v 2.0
c




      SUBROUTINE CDIFF1(IVAR)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER*4 KLC,KLV,KNL,IVAR
      COMMON/MDLA/MT(15)

      MT(1)=2
      MT(2)=2
      KLC= 0
      KLV= 0
      KNL=2
      RETURN
C     DEBUG SUBTRACE
      END


      SUBROUTINE CDIFF2(OM,P1,L1,P2,L2,P3,L3)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON/SUBC/Y(15,15),J(15)
      DOUBLE PRECISION P1    ,P2    ,P3    ,ZN
      DOUBLE COMPLEX Y,J
      DIMENSION P1(L1),P2(L2),P3(L3)

      Y(1,1)= DCMPLX(0.0D0,0.0D0)
      Y(1,2)= DCMPLX(0.0D0,0.0D0)
      Y(2,1)= DCMPLX(0.0D0,0.0D0)
      Y(2,2)= DCMPLX(0.0D0,0.0D0)
      RETURN
C     DEBUG SUBTRACE
      END


      SUBROUTINE CDIFF3(NG,P1,L1,P2,L2,P3,L3,B1,KNC2,NR,*)
C
C      SEMICONDUCTOR MATERIAL MODEL OF DIFFUSION CAPACITANCE APPROXIMATION
C
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DOUBLE PRECISION P1,P2,P3
      DIMENSION P1(L1),P2(L2),P3(L3)
      DOUBLE PRECISION B1
      DIMENSION B1(KNC2,NR)
      DOUBLE PRECISION TAU,I0,AL,ARGMIN/-120.0D0/,ARGMAX/40.0D0/

      C(U)=TAU*AL*I0*DEXP(AL*U)
      TAU=P3(1)
      I0=P3(2)
      AL=P3(3)
      DO 10 K=1,KNC2,2
      U=B1(K,1)
      B1(K,1)=0.0D0
      IF(U*AL.GT.ARGMAX) U=ARGMAX/AL
      IF(U*AL.GT.ARGMIN) B1(K,1)=C(U)*(1+AL*U)*B1(K,2)
      B1(K+1,1)=0.0D0
  10  B1(K+1,2)=0.0D0
      RETURN
C     DEBUG SUBTRACE,INIT(P1,L1,P2,L2,P3,L3,KNC2,NR,I0,AL)
      END


      SUBROUTINE CDIFF4(NG,P1,L1,P2,L2,P3,L3,B1,KNC2,NR,*)

C
C      SEE SEMICONDUCTOR CDIFF3
C

      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DOUBLE PRECISION P1,P2,P3
      DIMENSION P1(L1),P2(L2),P3(L3)
      DOUBLE PRECISION B1
      DIMENSION  B1(KNC2,NR)
      DOUBLE PRECISION I0,AL,ARGMIN/-120.0D0/,ARGMAX/40.0D0/
C                 $=MIN VALUE OF ARGUMENT OF EXP FUNCTION
      C(U)=TAU*AL*I0*DEXP(AL*U)
      TAU=P3(1)
      I0=P3(2)
      AL=P3(3)
      DO 10 K=1,KNC2,2
      U=B1(K,1)
      IF(U*AL.GT.ARGMAX) U=ARGMAX/AL
      IF(U*AL.LE.ARGMIN) GO TO 20
      B1(K,1)=C(U)*AL*(2.D0+AL*U)*B1(K,2)
      B1(K,2)=C(U)*(1.D0+AL*U)
      GO TO 15
   20 CONTINUE
      B1(K,1)=0.D0
      B1(K,2)=0.D0
   15 CONTINUE
      B1(K+1,1)=0.D0
      B1(K+1,2)=0.D0
   10 CONTINUE
      RETURN
C     DEBUG SUBTRACE
      END


      SUBROUTINE CDIFF5(NOI,NOU,EXIST,KOI,KOUV,KOPV,NR1V,NB1V)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER NOI(5,2),NOU(5,2)
      LOGICAL EXIST(5,2)
      INTEGER KOI,KOUV(5),KOPV(5),NR1V(5),NB1V(5)
      NOI(1,1)=1
      NOI(1,2)=2
      NOU(1,1)=1
      NOU(1,2)=2
      EXIST(1,1)=.TRUE.
      EXIST(1,2)=.TRUE.
      KOI    =1
      KOUV(1)=1
      KOPV(1)=1
      NR1V(1)=2
      NB1V(1)=2
      RETURN
      END


      SUBROUTINE CDIFF6(NG,P1,L1,P2,L2,P3,L3,VAL,DVAL,KN,NR,T)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DOUBLE PRECISION P1,P2,P3
      DOUBLE COMPLEX VAL,DVAL
      DIMENSION P1(L1),P2(L2),P3(L3)
      DIMENSION VAL(KN,NR),DVAL(KN,NR)
      DOUBLE PRECISION UOLD,UNEW,USTEP
      DOUBLE PRECISION DELTA,UBOUND,STEPM

      DELTA=0.01D0
      UBOUND=P3(4)
      STEPM=P3(5)

      UOLD=0.0D0
      UNEW=0.0D0
      IF(KN.LT.2)GO TO 15
      DO 10 I=2,KN
      UOLD=UOLD+ZABS(VAL(I,1))
   10 UNEW=UNEW+ZABS(VAL(I,1)+DVAL(I,1))
   15 CONTINUE
C                            $ MAYBE NEED NOT + A -
      UOLD=UOLD+UOLD+DREAL(VAL(1,1))
      UNEW=UNEW+UNEW+DREAL(VAL(1,1)+DVAL(1,1))
      USTEP=    UNEW-UOLD
C  MAYBE HERE $ NEED TO WRITE ABS(     )

      IF(UNEW.LE.UBOUND)RETURN
      IF(UOLD.LE.UBOUND)GO TO 20
      IF(USTEP.GT.STEPM)T=STEPM/USTEP
      RETURN
   20 T=(UBOUND+DELTA-UOLD)/USTEP
      RETURN
C     DEBUG SUBTRACE,INIT(          USTEP,T)
      END
