c
c Copyright (c) 1996-2004 by Gennady Serdyuk.  All rights reserved.
c gserdyuk@mail.ru
c
c Released under GPL v 2.0
c




C******** ITUN ON VAX I=I0*ALPHA*(EXP(AL*U)-1.0) ******************
C    USED FOR MODELING ITUNs IN
C    BIPOLAR TRANSISTORS.
      SUBROUTINE ICUJ1(IVAR)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER*4 KLC,KLV,KNL,IVAR
      COMMON/MDLA/MT(15)

      MT(1)=2
      MT(2)=2
      MT(3)=2
      MT(4)=2
      KLC= 0
      KLV= 0
      KNL=4
      RETURN
C     DEBUG SUBTRACE
      END


      SUBROUTINE ICUJ2(OM,P1,L1,P2,L2,P3,L3)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON/SUBC/Y(15,15),J(15)
      DOUBLE PRECISION P1    ,P2    ,P3    ,ZN
      DOUBLE COMPLEX Y,J
      DIMENSION P1(L1),P2(L2),P3(L3)

      DO 10 I=1,4
      DO 10 II=1,4
      Y(II,I)= DCMPLX(0.0D0,0.0D0)
  10  CONTINUE

      RETURN
C     DEBUG SUBTRACE
      END


      SUBROUTINE ICUJ3(NG,P1,L1,P2,L2,P3,L3,B1,KNC2,NR,*)
C
C      SUBROUTINE FOR THE MATHEMATICAL MODEL OF A BIPOLAR TRANSISTOR ITUN.
C          PROBABLY NEEDS AN APPROXIMATION
C          AT HIGH CURRENTS.
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DOUBLE PRECISION P1,P2,P3
      DIMENSION P1(L1),P2(L2),P3(L3)
      DOUBLE PRECISION B1
      DIMENSION B1(KNC2,NR)
      DOUBLE PRECISION I0,AL,ALPHA,ARGMAX/40.0D0/

      UN1(U)=ALPHA*I0*(DEXP(AL*U)-1)
      ALPHA=P3(1)
      I0=P3(2)
      AL=P3(3)

      DO 10 K=1,KNC2,2
      U=B1(K,1)
      IF(AL*U.GT.ARGMAX) U=ARGMAX/AL
      B1(K,1)=UN1(U)
   10 B1(K+1,1)=0.0D0
      RETURN
C     DEBUG SUBTRACE,INIT(P1,L1,P2,L2,P3,L3,KNC2,NR,I0,AL,ALPHA,U)
      END


      SUBROUTINE ICUJ4(NG,P1,L1,P2,L2,P3,L3,B1,KNC2,NR,*)

C
C      SEE SUBROUTINE ICUJ3
C

      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DOUBLE PRECISION P1,P2,P3
      DIMENSION P1(L1),P2(L2),P3(L3)
      DOUBLE PRECISION B1
      DIMENSION  B1(KNC2,NR)
      DOUBLE PRECISION I0,AL,ALPHA,ARGMIN/-120.0D0/,ARGMAX/40.0D0/
C                      $=MIN VALUE OF THE ARGUMENT OF THE EXP FUNCTION.

      DUN1(U)=ALPHA*AL*I0*DEXP(AL*U)
      ALPHA=P3(1)
      I0=P3(2)
      AL=P3(3)

      DO 10 K=1,KNC2,2
      U=B1(K,1)
      IF(AL*U.GT.ARGMAX) U=ARGMAX/AL
      B1(K,1)=0.0D0
      IF(U*AL.GT.ARGMIN) B1(K,1)= DUN1(U)
      B1(K+1,1)= 0.0D0
   10 CONTINUE
      RETURN
C     DEBUG SUBTRACE
      END


      SUBROUTINE ICUJ5(NOI,NOU,EXIST,KOI,KOUV,KOPV,NR1V,NB1V)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER NOI(5,2),NOU(5,2)
      LOGICAL EXIST(5,2)
      INTEGER KOI,KOUV(5),KOPV(5),NR1V(5),NB1V(5)
      NOI(1,1)=3
      NOI(1,2)=4
      NOU(1,1)=1
      NOU(1,2)=2
      EXIST(1,1)=.TRUE.
      EXIST(1,2)=.FALSE.
      KOI    =1
      KOUV(1)=1
      KOPV(1)=0
      NR1V(1)=1
      NB1V(1)=1
      KGR=1
      RETURN
      END


      SUBROUTINE ICUJ6(NG,P1,L1,P2,L2,P3,L3,VAL,DVAL,KN,NR,T)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DOUBLE PRECISION P1,P2,P3
      DOUBLE COMPLEX VAL,DVAL
      DIMENSION P1(L1),P2(L2),P3(L3)
      DIMENSION VAL(KN,NR),DVAL(KN,NR)
      DOUBLE PRECISION UOLD,UNEW,USTEP
      DOUBLE PRECISION DELTA,UBOUND,STEPM

      DELTA=0.01D0
      UBOUND=P3(4)
      STEPM=P3(5)

      UOLD=0.0D0
      UNEW=0.0D0
      IF(KN.LT.2)GO TO 15
      DO 10 I=2,KN
      UOLD=UOLD+ZABS(VAL(I,1))
   10 UNEW=UNEW+ZABS(VAL(I,1)+DVAL(I,1))
   15 CONTINUE
C                            $ MAY NEED NOT + BUT -
      UOLD=UOLD+UOLD+DREAL(VAL(1,1))
      UNEW=UNEW+UNEW+DREAL(VAL(1,1)+DVAL(1,1))
      USTEP=    UNEW-UOLD
C  MAYBE HERE $ NEEDS TO BE REPLACED WITH ABS(     )

      IF(UNEW.LE.UBOUND)RETURN
      IF(UOLD.LE.UBOUND)GO TO 20
      IF(USTEP.GT.STEPM)T=STEPM/USTEP
      RETURN
   20 T=(UBOUND+DELTA-UOLD)/USTEP
      RETURN
C     DEBUG SUBTRACE,INIT(          USTEP,T)
      END
