c
c Copyright (c) 1996-2004 by Gennady Serdyuk.  All rights reserved.
c gserdyuk@mail.ru
c
c Released under GPL v 2.0
c





      SUBROUTINE JUNC1(IVAR)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER*4 KLC,KLV,KNL,IVAR
      COMMON/MDLA/MT(15)

      MT(1)=2
      MT(2)=2
      KLC= 0
      KLV= 0
      KNL=2
      RETURN
C     DEBUG SUBTRACE
      END


      SUBROUTINE JUNC2(OM,P1,L1,P2,L2,P3,L3)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON/SUBC/Y(15,15),J(15)
      DOUBLE PRECISION P1    ,P2    ,P3    ,ZN
      DOUBLE COMPLEX Y,J
      DIMENSION P1(L1),P2(L2),P3(L3)

C  JUNC = DIODE WITHOUT NONLINEAR CAPACITANCE
      Y(1,1)= DCMPLX(0.0D0,0.0D0)
      Y(1,2)= DCMPLX(0.0D0,0.0D0)
      Y(2,1)= DCMPLX(0.0D0,0.0D0)
      Y(2,2)= DCMPLX(0.0D0,0.0D0)
      RETURN
C     DEBUG SUBTRACE
      END


      SUBROUTINE JUNC3(NG,P1,L1,P2,L2,P3,L3,B1,KNC2,NR,*)

C
C      ITEM MAT. MODELS OF SCHOTTKY CONTACT (WITHOUT CAPACITANCE)
C          PROBABLY HAVE TO INTRODUCE AN APPROXIMATION
C          AT HIGH CURRENTS. DON'T FORGET ABOUT JUNC4
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DOUBLE PRECISION P1,P2,P3
      DIMENSION P1(L1),P2(L2),P3(L3)
      DOUBLE PRECISION ARGMAX/40.D0/
      DOUBLE PRECISION B1
      DIMENSION B1(KNC2,NR)
      DOUBLE PRECISION I0,AL
      DUN(U)=I0*AL*DEXP(AL*U)
      UN1(U)=I0*(DEXP(AL*U)-1)
      I0=P3(1)
      AL=P3(2)
C
      DO 10 K=1,KNC2,2
      U=B1(K,1)
      IF(AL*U.LE.ARGMAX)GO TO 5
      UM=ARGMAX/AL
      B1(K,1)=UN1(UM)+DUN(UM)*(U-UM)
      GO TO 10
    5 B1(K,1)=UN1(U)
   10 B1(K+1,1)=0.0D0
      RETURN
C     DEBUG SUBTRACE,INIT(P1,L1,P2,L2,P3,L3,KNC2,NR,I0,AL)
      END


      SUBROUTINE JUNC4(NG,P1,L1,P2,L2,P3,L3,B1,KNC2,NR,*)

C
C      SEE ITEM JUNC3
C

      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DOUBLE PRECISION P1,P2,P3
      DIMENSION P1(L1),P2(L2),P3(L3)
      DOUBLE PRECISION B1
      DIMENSION  B1(KNC2,NR)
      DOUBLE PRECISION I0,AL,ARGMIN/-120.0D0/,ARGMAX/40.D0/
C                 $=MIN VALUE OF THE ARGUMENT OF THE EXP FUNCTION.
      DUN1(U)=AL*I0*DEXP(AL*U)
      I0=P3(1)
      AL=P3(2)

      DO 10 K=1,KNC2,2
      U=B1(K,1)
      B1(K,1)=0.0D0
      IF(U*AL.GT.ARGMIN.AND.U*AL.LT.ARGMAX) B1(K,1)= DUN1(U)
      IF(U*AL.GT.ARGMAX) B1(K,1)=DUN1(ARGMAX/AL)
      B1(K+1,1)= 0.0D0
   10 CONTINUE
      RETURN
C     DEBUG SUBTRACE
      END


      SUBROUTINE JUNC5(NOI,NOU,EXIST,KOI,KOUV,KOPV,NR1V,NB1V)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER NOI(5,2),NOU(5,2)
      LOGICAL EXIST(5,2)
      INTEGER KOI,KOUV(5),KOPV(5),NR1V(5),NB1V(5)
      NOI(1,1)=1
      NOI(1,2)=2
      NOU(1,1)=1
      NOU(1,2)=2
      EXIST(1,1)=.TRUE.
      EXIST(1,2)=.FALSE.
      KOI    =1
      KOUV(1)=1
      KOPV(1)=0
      NR1V(1)=1
      NB1V(1)=1
      KGR=1
      RETURN
      END


      SUBROUTINE JUNC6(NG,P1,L1,P2,L2,P3,L3,VAL,DVAL,KN,NR,T)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DOUBLE PRECISION P1,P2,P3
      DOUBLE COMPLEX VAL,DVAL
      DIMENSION P1(L1),P2(L2),P3(L3)
      DIMENSION VAL(KN,NR),DVAL(KN,NR)
      DOUBLE PRECISION UOLD,UNEW,USTEP
      DOUBLE PRECISION DELTA,UBOUND,STEPM

      DELTA=0.01D0
      UBOUND=P3(3)
      STEPM=P3(4)

      UOLD=0.0D0
      UNEW=0.0D0
      IF(KN.LT.2)GO TO 15
      DO 10 I=2,KN
      UOLD=UOLD+ZABS(VAL(I,1))
   10 UNEW=UNEW+ZABS(VAL(I,1)+DVAL(I,1))
   15 CONTINUE
C                            $ MAYBE NEED NOT + BUT -
      UOLD=UOLD+UOLD+DREAL(VAL(1,1))
      UNEW=UNEW+UNEW+DREAL(VAL(1,1)+DVAL(1,1))
      USTEP=    UNEW-UOLD
C  MAYBE HERE $ NEED TO PUT ABS(     )

      IF(UNEW.LE.UBOUND)RETURN
      IF(UOLD.LE.UBOUND)GO TO 20
      IF(USTEP.GT.STEPM)T=STEPM/USTEP
      RETURN
   20 T=(UBOUND+DELTA-UOLD)/USTEP
      RETURN
C     DEBUG SUBTRACE,INIT(UOLD,UNEW,UBOUND,STEPM,USTEP,T)
      END
