c
c Copyright (c) 1996-2004 by Gennady Serdyuk.  All rights reserved.
c gserdyuk@mail.ru
c
c Released under GPL v 2.0
c




      SUBROUTINE SUPRIM(T,U,DELTU)
C                                                                 *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      EQUIVALENCE (K3,KOL(3))
      include 'circuit.i'

      COMMON/KOLNAL/KOL(4),NAL(4)
      LOGICAL NAL
      COMMON/BLK1/KR,KR1,KC,KC1,NNR,NNR1,MN,MN1
      COMMON/BLK2/KNC,KNR,KN,KNR1,KN1
      COMMON/BLW1/W,W1/BLW2/WR,WS
      DOUBLE PRECISION W(20),W1(200)
      INTEGER KR(20),KC(10),NNR(10),MN(2,20)
      INTEGER KR1(200),KC1(20),NNR1(20),MN1(2,200)
      INTEGER WR(20,20),WS(20,20)
      INTEGER NAME(4),NOI(5,2),NOU(5,2),NU1(5,2),NU2(5,2)
      INTEGER KOUV(5),KOPV(5),KOI,NR1V(5),NB1V(5),NG,INDEP
      DOUBLE PRECISION T,T1
      DOUBLE COMPLEX U,DELTU
      DIMENSION U(1),DELTU(1)
      DOUBLE COMPLEX VAL(150),DVAL(150)
      DOUBLE COMPLEX IM/(0.0D0,1.0D0)/,ZERO/(0.0D0,0.0D0)/
      DOUBLE COMPLEX U1,U2,DU1,DU2
      LOGICAL EXS(5,2),EXIST(5,2)
      INTEGER LENF/30/,DMDFDX/50/
C     PRINT 26,(U(JJJ),DELTU(JJJ),JJJ=1,2 )
C  26 FORMAT('   U:',2E14.6,'  DELTU:',2E14.6 )
      N1=NNETPR
      L1=LENNTP
      KUR=KN*K3
      T=1.D0
C  LOOP FOR SEARCHING NONLINEAR ELEMENTS
C  COMPUTATION OF STEP FOR SEARCHING NONLINEAR ELEMENTS.
C  NMPNT - NUMBER OF TYPES OF ELEMENTS.
      I1END=20*NMPNT
      DO 100 I1=1,I1END,20
      IF(MPOINT(I1+5).NE.3) GO TO 100
C  IF A LINEAR ELEMENT IS FOUND, GO TO LABEL ..100..
      I2E=MPOINT(I1+4)
C  I2E - NUMBER OF ELEMENTS OF THIS TYPE.
      IF(I2E.EQ.0)GO TO 100
      NF=MPOINT(I1+9)
      LE=MPOINT(I1+6)
      N2=MPOINT(I1+11)
C  L2-NUMBER OF PARAMETERS OF THIS TYPE OF ELEMENTS.
      L2=MPOINT(I1+10)
C  DETERMINATION OF THE NAME OF THE ELEMENT TYPE
      NAME(1)=MPOINT(I1)
      NAME(2)=MPOINT(I1+1)
      NAME(3)=MPOINT(I1+2)
      NAME(4)=MPOINT(I1+3)
      CALL LIBMD5(NAME,NOI,NOU,EXIST,KOI,KOUV,KOPV,NR1V,NB1V)
C  LOOP OVER ELEMENTS OF THE TYPE
      DO 110 I2=1,I2E
      L3=MPOINT(I1+12)
      KNODES=MPOINT(I1+7)
      NA=NF+(I2-1)*LE
      N3=NODEEL(NA+KNODES+3)
C  LOOP OVER INDEPENDENT GROUPS OF SOURCES
      NADRU=1
      DO 110 INDEP=1,KOI
      NG=INDEP
      KOI=1
      KOU=KOUV(NG)
      KOP=KOPV(NG)
      NR=KOU+KOP
      NB=KOI
      NR1=NR1V(NG)
      NB1=NB1V(NG)
C  DETERMINATION OF THE NODE NUMBER FOR THE APPLICATION OF CONTROL
C  VOLTAGE (NU1) AND CURRENT (NU2)
C  AND TRANSFER OF FLAGS FROM EXIST TO EXS RELATED TO THE CURRENT
C   GROUP
      DO 22 I=1,KOU
      NU1(I,1)=NODEEL(NA+NOU(NADRU,1))
      NU1(I,2)=NODEEL(NA+NOU(NADRU,2))
      EXS(I,1)=EXIST(NADRU,1)
      EXS(I,2)=EXIST(NADRU,2)
   22 NADRU=NADRU+1
      NU2(INDEP,1)=NODEEL(NA+NOI(INDEP,1))
      NU2(INDEP,2)=NODEEL(NA+NOI(INDEP,2))

C  FILLING VAL, DVAL
C        TOTAL: VAL(KN*(KOU+KOP))
C              DVAL(KN*(KOU+KOP))
C
C     MPOINT(I1+17)=KOU+KOP
      KUNEL=KN*KOU
      KDUN=KN*KOP
      KVAL=NR*KN
      DO 30 I=1,KVAL
      VAL(I)=ZERO
   30 DVAL(I)=ZERO
C  FILLING VAL, DVAL
C  FILLED WITH KOU 'BLOCKS' ...
      IDU=0
      DO 40 IU=1,KOU
      IUBEG=(IU-1)*KN
C  BY KN ELEMENTS
      DO 43 JW=1,KN
      JWBEG=(JW-1)*K3
      U1=ZERO
      U2=ZERO
      DU1=ZERO
      DU2=ZERO
      IF(NU1(IU,1).EQ.0) GOTO 46
      U1=U(JWBEG+NU1(IU,1))
      DU1=DELTU(JWBEG+NU1(IU,1))
   46 CONTINUE
      IF(NU1(IU,2).EQ.0) GOTO 48
      U2=U(JWBEG+NU1(IU,2))
      DU2=DELTU(JWBEG+NU1(IU,2))
   48 CONTINUE
      VAL(IUBEG+JW)=U1-U2
      DVAL(IUBEG+JW)=DU1-DU2
   43 CONTINUE
      IF(.NOT.EXS(IU,2)) GO TO 40
      IDU=IDU+1
      DO 47 JW=1,KN
      IDUBEG=(IDU-1)*KN
      ITERM=KUNEL+IDUBEG
      VAL(ITERM+JW)=IM*W(JW)*VAL(IUBEG+JW)
      DVAL(ITERM+JW)=IM*W(JW)*DVAL(IUBEG+JW)
   47 CONTINUE
   40 CONTINUE
C  IN THE LIST OF PARAMETERS LIBMD5, A CHECK IS MADE: 'IS THERE A CONTROL STEP?'
      T1=T
      CALL LIBMD6(NAME,NG,N1,L1,N2,L2,N3,L3,VAL,DVAL,KN,NR,T1)
      T=DMIN1(T,T1)
  110 CONTINUE
  100 CONTINUE
C  MULTIPLY Y BY T
      DO 210 I=1,KUR
  210 DELTU(I)=DELTU(I)*T
      RETURN
C     DEBUG SUBTRACE,INIT(T,T1)
      END
