c
c Copyright (c) 1996-2004 by Gennady Serdyuk.  All rights reserved.
c gserdyuk@mail.ru
c
c Released under GPL v 2.0
c




      SUBROUTINE STOP(N,X,DX,F,FNOR,G,SX,SF,IRETCD,ITER,MAXTKN,
     +       KMAXDU,TERMCD)
C
C   SUBROUTINE FOR DETERMINING THE REASON FOR STOPPING.
C     * TERMCD=0 - NO STOP;
C       ...

      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON/PRINT /   KPRLEN,KPRSRT,KPRNKR,KPRLIN,KPRSOL,KPRVAR,
     +          KPRGRF,KPRQUP
      COMMON/NEWTON/   EPSSOL,EPSDU,EPSMIN,MAXDU,LIMIT
      DOUBLE PRECISION             EPSSOL,EPSDU,EPSMIN,MAXDU
      INTEGER          TERMCD
      LOGICAL          MAXTKN
      DOUBLE PRECISION             X(1),DX(1),F(1),G(1)
      DOUBLE PRECISION             SX(1),SF(1)

      TERMCD=0

      IF(IRETCD.NE.1)GOTO 10
C  IN LSERCH WE FAILED TO MAKE A SATISFACTORY STEP
C        SCHA
      TERMCD=3
      IF(KPRSOL.GT.0) WRITE(6, 103) ITER,EPSDU,FNOR
                      PRINT    103, ITER,EPSDU,FNOR
      RETURN
  10  CONTINUE

C  MAXIMUM SCALED RESIDUAL TERM:
      CONV=0.D0
      DO 20 I=1,N
  20  CONV=DMAX1(CONV,SF((I+1)/2)*DABS(F(I)))
      IF(CONV.GT.EPSSOL) GOTO 30
C  WE HAVE AN APPROXIMATE SOLUTION
C   (IF EPSSOL IS NOT VERY SMALL)
      TERMCD=1
      IF(KPRSOL.GT.0) WRITE(6, 101) ITER,CONV,EPSSOL,FNOR
                      PRINT    101, ITER,CONV,EPSSOL,FNOR
      RETURN
  30  CONTINUE

C  MAXIMUM SCALED CORRECTION TERM
      DUNOR=0.D0
      DO 40 I=1,N
      SINV=1/SX((I+1)/2)
  40  DUNOR=DMAX1(DUNOR,DABS(DX(I)/DMAX1(DABS(X(I)),SINV)))
      IF(DUNOR.GT.EPSDU) GOTO 50
C  CORRECTION IS LESS THAN THE MINIMUM ALLOWED.
      TERMCD=2
      IF(KPRSOL.GT.0) WRITE(6, 102) ITER,DUNOR,EPSDU,CONV,FNOR
                      PRINT    102, ITER,DUNOR,EPSDU,CONV,FNOR
      RETURN
  50  CONTINUE

      IF(ITER.LT.LIMIT)GOTO 60
C  ITERATION LIMIT EXHAUSTED
      TERMCD=4
      IF(KPRSOL.GT.0) WRITE(6, 104) ITER,CONV,EPSSOL,DUNOR,EPSDU
                      PRINT    104, ITER,CONV,EPSSOL,DUNOR,EPSDU
      RETURN
  60  CONTINUE

      IF(.NOT.MAXTKN)GOTO 70
C  A STEP OF LENGTH MAXDU WAS TAKEN
      KMAXDU=KMAXDU+1
      IF(KMAXDU.LT.5)GOTO 70
C  FIVE STEPS OF LENGTH MAXDU WERE TAKEN
      TERMCD=5
      IF(KPRSOL.GT.0) WRITE(6, 105) ITER,MAXDU,CONV,EPSSOL
                      PRINT    105, ITER,MAXDU,CONV,EPSSOL
      RETURN
  70  CONTINUE

      KMAXDU=0
C   DEFINITION OF THE REQUIRED DECREASE IN FNOR
      TERM=0.D0
      DO 80 I=1,N
      SINV=1/SX((I+1)/2)
      TERM=DMAX1(TERM,DABS(G(I))*DMAX1(X(I)      ,SINV)/
     + DMAX1(FNOR,DFLOAT(N)/2.D0))
C     REMOVED PRINT 222 C WITH FORMAT 8.12.89. KOSCHMANOVA N.W. *****
  80  CONTINUE
      IF(TERM.GT.EPSMIN)GOTO 90
C   SO, WE ARE AT THE LOCAL MINIMUM OF FNOR.
      TERMCD=6
      IF(KPRSOL.GT.0) WRITE(6, 106) ITER,TERM,EPSMIN,FNOR,CONV,EPSSOL
                      PRINT    106, ITER,TERM,EPSMIN,FNOR,CONV,EPSSOL
      RETURN
  90  CONTINUE
C   NOTHING HAPPENED
      IF(KPRSOL.GE.2) WRITE(6, 107) CONV,DUNOR,TERM
                      PRINT    107, CONV,DUNOR,TERM
      RETURN
 101  FORMAT('     AT ',I5,' -TH ITERATION CONVERGED TO '/       '  SOLU
     +TION WITH ERROR <= ',E13.6 ,' ( < ',E13.6,' )'/       '  1/2 OF SQ
     +UARED L-2 NORM OF ERROR =',E13.6 )
 102  FORMAT('     AT ',I5,' -T ITERATION MAX STEP=',E13.6,' ( <',E13.6,
     +')'/       '  ERROR =',E13.6/       '  1/2 OF SQUARED L-2 NORM OF
     +ERROR =',E13.6)
 103  FORMAT('     AT ',I5,' -TH ITERATION CAN NOT MAKE GOOD STEP'/
     +  '  > ',E13.6/       '  1/2 OF SQUARED L-2 NORM OF ERROR =',E13.6
     +)
 104  FORMAT('     ITERATION LIMIT:',I4,' IS REACHED.'/       '  ERROR =
     +',E13.6,'( > ',E13.6,' );'/       '  STEP =',E13.6,'( > ',E13.6,'
     +).')
 105  FORMAT('     AT ',I4,' ITERATION , IT IS MADE'/       '  5 STEPS O
     +F LENGTH ',E13.6/       '  ERROR =',E13.6,' ( > ',E13.6,' ).')
 106  FORMAT('  IT IS LOCAL MINIMUM :  '/       '              ITERATION
     +                        ',I4/       '              GRADIENT OF ERR
     +OR NORM        ',E13.6,
     +    '(<',E13.6 ,')'/       '              1/2 SQUARED  L-2 ERROR N
     +ORM   ',E13.6/       '               ERROR
     +',E13.6/       '               REQUIRED                     ',E13.
     +6)

 107  FORMAT(' ERROR  =',E13.6,', STEP=',E13.6,', SPEED OF DECREASING='
     +      , E13.6)



C     DEBUG SUBTRACE,INIT
      END
