c
c Copyright (c) 1996-2004 by Gennady Serdyuk.  All rights reserved.
c gserdyuk@mail.ru
c
c Released under GPL v 2.0
c



      SUBROUTINE DECODE(U,NOHAR,ISIZE_MAXNODE)
C
C  SUBROUTINE FOR PERMUTING ELEMENTS OF THE SOLUTION VECTOR
C  WITHIN THE VECTOR ITSELF TO MATCH THE NODE NUMBERING
C  WITH THE ORIGINAL NUMBERING.
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON/KOLNAL/KOL,NAL
      COMMON/NOUZL /NOUZ,INOUZ1

      LOGICAL NAL(4)
      INTEGER ISIZE_MAXNODE
      INTEGER KOL(4),NTOT,NOUZ(100),INOUZ1(100),TERM
      DOUBLE COMPLEX S,U(1),UT(ISIZE_MAXNODE)

C  TOTAL NUMBER OF NODES:
      NTOT=KOL(1)+KOL(2)+KOL(3)
C     WRITE(6, 810) (IVA,NOUZ(IVA),IVA=1,NTOT)
C 810 FORMAT(2X,'DECODE: NOUZ(',I3,')=',I4)
C     WRITE(6, 815) NTOT
C 815 FORMAT(2X,'NTOT=',I5)

C  IN ALL NODES
      DO 10 I=1,NTOT
C  PERFORM PERMUTATION FROM U TO UT IN ACCORDANCE WITH
C  THE MAPPING VECTOR NOUZ    /SEE SUBROUTINE SORTUZ/
      TERM=NOUZ(I)
   10 UT(TERM)=U(I)
C  NOW COPY FROM THE TEMPORARY VECTOR UT
C  INTO THE SOLUTION VECTOR U:
      DO 15 I=1,NTOT
C     WRITE(6, 14) I,UT(I)
C  14 FORMAT(2X,'DECODE: U(',I3,')=',E12.5,2X,E12.5)
   15 U(I)=UT(I)
      RETURN
C     DEBUG SUBTRACE,SUBCHK,INIT(I,TERM)
      END
