c
c Copyright (c) 1996-2004 by Gennady Serdyuk.  All rights reserved.
c gserdyuk@mail.ru
c
c Released under GPL v 2.0
c




      SUBROUTINE RESTOR(U,Y,VECTJ,ISIZE_MAXNODE,S)

C     SUBROUTINE FOR CALCULATING THE CURRENTS OF NODES AND STRESSES IN THE EXTERNAL NODES,
C     AND ALSO THE CALCULATION OF THE STRESS CURRENTS. IN ACCORDANCE WITH THE USER NUMBER.

      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON/KOLNAL/   KOL(4),NAL(4)
      COMMON/BLK2  /   KNC,KNR,KN,KNR1,KN1
      LOGICAL          NAL
      INTEGER          KOL,K12,KNC,KNR,KN,KNR1,KN1,IRC
      INTEGER ISIZE_MAXNODE
      DOUBLE COMPLEX  S(ISIZE_MAXNODE,20)
      DOUBLE PRECISION U(1)

      DOUBLE COMPLEX Y(ISIZE_MAXNODE,ISIZE_MAXNODE)
      DOUBLE COMPLEX VECTJ(ISIZE_MAXNODE)
C      PRINT 3
C    3 FORMAT(2X,'ENTRY INTO THE SUBROUTINE RESTOR')

      K12=KOL(1)+KOL(2)
      CALL TOPO(1,K12)
      DO 5 J=1,KN
      IRC=J
C      print *, 'RESTOR: IRC: ', IRC
      CALL STBACK(U,IRC,Y,VECTJ,ISIZE_MAXNODE,S)
    5 CALL DECODE(S(1,IRC),IRC,ISIZE_MAXNODE)
      RETURN

      END
